cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  name: ${NODE_NAME}
  data: ${NODE_DATA}
  ingest: ${NODE_INGEST}

network.host: ${NETWORK_HOST}

indices.breaker.fielddata.limit: 85%
indices.fielddata.cache.size:  75%

path:
  data: /data/data
  logs: /data/log

http:
  enabled: true
  compression: true

discovery:
  zen:
    ping.unicast.hosts: ${DISCOVERY_SERVICE}
    minimum_master_nodes: ${NUMBER_OF_MASTERS}